<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ASUS" ignored="0" name="Login Test" tests="3" failures="1" timestamp="2022-12-12T14:42:47 GMT" time="12.542" errors="0">
  <testcase name="UserSholdLoginSuccessfullyWithValidCredentials" time="0.537" classname="com.herokuapp.internet.testsuite.LoginPageTest"/>
  <testcase name="verifyThePasswordErrorMessage" time="0.472" classname="com.herokuapp.internet.testsuite.LoginPageTest"/>
  <testcase name="verifyTheUserNameErrorMessage" time="0.489" classname="com.herokuapp.internet.testsuite.LoginPageTest">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.herokuapp.internet.testsuite.LoginPageTest.verifyTheUserNameErrorMessage(LoginPageTest.java:37)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- verifyTheUserNameErrorMessage -->
</testsuite> <!-- Login Test -->
